### ISSUE TITLE
what does the plugin do

### ISSUE THREAD

**Issue by susl16c** [lolnetnz/Forum#1]
what does the plugin do

**Comment by LXGaming** [comment]
This XenForo 2 addon was specifically created for Lolnet.

Currently the plugin does two things:
- Verifies custom user field data. This includes length, characters and checking for duplicates as the fields are unique to each user.
- Modifies PayPal Payment class to go to a donation page instead of a payment page.

This addon won't be something you can just drop onto your own Forum, It's on GitHub to provided more code examples as the XenForo documentation is somewhat lacking.
